### ISSUE TITLE
seenCache drops messages too early

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/js-libp2p-gossipsub#161]
Debugging for an unrelated problem (https://github.com/ChainSafe/lodestar/issues/3110) I noticed the cache keeps items for too little.

@wemeetagain noticed it keeps items for 30 seconds.

- [ ] Consider dropping time cache completely for a simpler solution
- [ ] Consult with other teams a proper timeouts or follow the spec https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#the-gossip-domain-gossipsub

See below the message `block 2046119 (new) FdqanLvU71cfZa2GBXOd7TOPJ8c`, it's (new) and repeated

```
                  >>> Gossipssub - block 2046119 (new)           16.68s late FdqanLvU71cfZa2GBXOd7TOPJ8c Lighthouse/v1.5.0-90d5ab1/aarch64-linux 16Uiu2HAmBi4CiFxB9zQbEx4mkbGiE9bwSaaZ9nGZX8RhRGPXL2fh
Eph 63941/8 4.700 [CHAIN]            info: Received block: 2046119
Eph 63941/8 6.014 []                 info: Synced - block: 2046120   … (empty) - head: 2046119 0xe042…490b - finalized: 2046048 0x7916…f846 (63939) - peers: 14
                  >>> Gossipssub - block 2046114 (already known) 80.33s late AhdyuZn7FP8Ml6pgd2o6IZPzPSs Lighthouse/v1.5.0-90d5ab1+/x86_64-linux 16Uiu2HAmCWxz9iXTrstyF1YDbvmpN6ngG2R3cTw6bTAXMLZEN2b8
                  >>> Gossipssub - block 2046114 (already known) 80.34s late AhdyuZn7FP8Ml6pgd2o6IZPzPSs Lighthouse/v1.5.0-90d5ab1/x86_64-linux 16Uiu2HAmJj6y2ces4gjhRzPFXBEqRdB6NoKWSh3B1Mgevr41c4WA
                  >>> Gossipssub - block 2046114 (already known) 80.34s late AhdyuZn7FP8Ml6pgd2o6IZPzPSs rust-libp2p/0.31.0 16Uiu2HAm3gcqtY6W5717jFQXSfcHkMzGYAag8XuYgcqgDCebeFbz
                  >>> Requesting peer beacon_block IWANT 16Uiu2HAm2KKqQj4PdHEZoRegyRzTegTqDBuzHcPwp4foesYtzkvE [ 'L9aYtlGZxVxHBuNjtVR/3gHfth4' ]
                  >>> Gossipssub - block 2046115 (new)           72.12s late AH+MpdqfVsFB/nogYJhkIEdrWZM Prysm/v1.4.2/b3650903ea23b040928732a2bed8b75d584ba903 16Uiu2HAkybvBXJbc9dfmU5spX9yV79Nv44hEQxFiHiEpCmFZR7jA
Eph 63941/9 0.364 [SYNC]             info: INFURA HEAD 2046121, delay 0.3640000820159912s
                  >>> Requesting peer beacon_block IWANT 16Uiu2HAm2KKqQj4PdHEZoRegyRzTegTqDBuzHcPwp4foesYtzkvE [ 'DYodRUy6nfRhpLYdNLTTYqYqFCs' ]
                  >>> Gossipssub - block 2046121 (new)            0.88s late M1lw4SOUyZFV8rGS79oDyupTZCA Prysm/v1.4.1/a9ee3ee06afdffa2a9b0e759d4142642e7488416 16Uiu2HAm2KKqQj4PdHEZoRegyRzTegTqDBuzHcPwp4foesYtzkvE
Eph 63941/9 0.899 [CHAIN]            info: Received block: 2046121
Eph 63941/9 0.901 [CHAIN]           error: Block error slot=2046121, errCode=BLOCK_ERROR_PARENT_UNKNOWN
Eph 63941/9 1.265 [ETH1]            error: Error updating eth1 chain cache message=The user aborted a request.
AbortError: The user aborted a request.
    at abort (/home/lion/Code/eth2.0/lodestar/node_modules/node-fetch/lib/index.js:1418:16)
    at AbortSignal.abortAndFinalize (/home/lion/Code/eth2.0/lodestar/node_modules/node-fetch/lib/index.js:1433:4)
    at AbortSignal.dispatchEvent (/home/lion/Code/eth2.0/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
    at abortSignal (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/abort-controller/src/abort-signal.ts:68:12)
    at AbortController.abort (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/abort-controller/src/abort-controller.ts:26:9)
    at Timeout._a (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:107:18)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
Eph 63941/9 1.934 [CHAIN]            info: Received block: 2046120
                  >>> Gossipssub - block 2046115 (already known) 76.10s late AH+MpdqfVsFB/nogYJhkIEdrWZM Prysm/v1.4.4/29d48dfe7eb38959752048aec700f31c3abf7484 16Uiu2HAmH3MSFR4ijLotNJ6qML15uVRqGxkr5S19UUJrp3vmaTSQ
Eph 63941/9 6.000 []                 info: Synced - block: 2046121 0xa78e…0393 - head: 2046121 0xa78e…0393 - finalized: 2046048 0x7916…f846 (63939) - peers: 13
                  >>> Gossipssub - block 2046115 (already known) 82.79s late AH+MpdqfVsFB/nogYJhkIEdrWZM Lighthouse/v1.5.0-90d5ab1/x86_64-linux 16Uiu2HAmJj6y2ces4gjhRzPFXBEqRdB6NoKWSh3B1Mgevr41c4WA
                  >>> Gossipssub - block 2046115 (already known) 82.79s late AH+MpdqfVsFB/nogYJhkIEdrWZM rust-libp2p/0.31.0 16Uiu2HAm3gcqtY6W5717jFQXSfcHkMzGYAag8XuYgcqgDCebeFbz
Eph 63941/10 0.424 [SYNC]             info: INFURA HEAD 2046122, delay 0.4240000247955322s
                  >>> Gossipssub - block 2046116 (new)           74.16s late OLcXFZm0n6fyIJoIAFo538tsDMg Prysm/v1.4.2/b3650903ea23b040928732a2bed8b75d584ba903 16Uiu2HAkybvBXJbc9dfmU5spX9yV79Nv44hEQxFiHiEpCmFZR7jA
Eph 63941/10 6.001 []                 info: Synced - block: 2046122   … (empty) - head: 2046121 0xa78e…0393 - finalized: 2046048 0x7916…f846 (63939) - peers: 14
                  >>> Gossipssub - block 2046116 (already known) 78.10s late OLcXFZm0n6fyIJoIAFo538tsDMg Prysm/v1.4.4/29d48dfe7eb38959752048aec700f31c3abf7484 16Uiu2HAmH3MSFR4ijLotNJ6qML15uVRqGxkr5S19UUJrp3vmaTSQ
                  >>> Gossipssub - block 2046120 (new)           31.11s late 1zuLxwl+Rng+EuPfSDwtZySj0D4 Lighthouse/v1.5.0-90d5ab1/aarch64-linux 16Uiu2HAmBi4CiFxB9zQbEx4mkbGiE9bwSaaZ9nGZX8RhRGPXL2fh
Eph 63941/11 1.066 [SYNC]             info: INFURA HEAD 2046123, delay 1.065999984741211s
                  >>> Gossipssub - block 2046117 (new)           75.91s late NfWh1gqsh3z2rFOZBXpom78S1iQ Prysm/v1.4.2/b3650903ea23b040928732a2bed8b75d584ba903 16Uiu2HAkybvBXJbc9dfmU5spX9yV79Nv44hEQxFiHiEpCmFZR7jA
                  >>> Gossipssub - block 2046116 (already known) 88.62s late OLcXFZm0n6fyIJoIAFo538tsDMg Lighthouse/v1.5.0-90d5ab1/x86_64-linux 16Uiu2HAmJj6y2ces4gjhRzPFXBEqRdB6NoKWSh3B1Mgevr41c4WA
                  >>> Gossipssub - block 2046116 (already known) 88.75s late OLcXFZm0n6fyIJoIAFo538tsDMg rust-libp2p/0.31.0 16Uiu2HAm3gcqtY6W5717jFQXSfcHkMzGYAag8XuYgcqgDCebeFbz
Eph 63941/11 6.001 []                 info: Synced - block: 2046123   … (empty) - head: 2046121 0xa78e…0393 - finalized: 2046048 0x7916…f846 (63939) - peers: 14
                  >>> Gossipssub - block 2046118 (new)           70.53s late mNPQQTZJ5WUwTRI/pl6ZE8c+8vA Prysm/v1.4.2/b3650903ea23b040928732a2bed8b75d584ba903 16Uiu2HAkybvBXJbc9dfmU5spX9yV79Nv44hEQxFiHiEpCmFZR7jA
Eph 63941/12 0.704 [SYNC]             info: INFURA HEAD 2046124, delay 0.7039999961853027s
                  >>> Gossipssub - block 2046119 (new)           65.38s late FdqanLvU71cfZa2GBXOd7TOPJ8c Prysm/v1.4.2/b3650903ea23b040928732a2bed8b75d584ba903 16Uiu2HAkybvBXJbc9dfmU5spX9yV79Nv44hEQxFiHiEpCmFZR7jA
```

**Comment by dapplion** [comment]
Current gossipsub version keeps messages the expected amount of time
