### ISSUE TITLE
CI: go-gossipsub tests failed

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#178]
Sometimes the CI failed with

```
 1) go-libp2p-pubsub gossipsub tests
       test gossipsub flood publish:
     Error: Message never received, sender 0, receiver 0, index 0
      at Timeout._onTimeout (test\go-gossipsub.js:43:14)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

**Comment by tuyennhv** [comment]
other error:

```
 1) test gossipsub direct peers


  15 passing (5m)
  1 pending
  1 failing

  1) go-libp2p-pubsub gossipsub tests
       test gossipsub direct peers:
     Error: Message never received, sender 0, receiver 0, index 0
      at Timeout._onTimeout (test/go-gossipsub.js:61:14)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```
