### ISSUE TITLE
Got this failed unit test (happened only on browsers) with libp2p 0.36.2

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#191]
Got this failed unit test (happened only on browsers) with libp2p 0.36.2

```
2 nodes
    basics
      1) Dial from nodeA to nodeB happened with pubsub
  0 passing (2s)
  1 failing
  1) 2 nodes
       basics
         Dial from nodeA to nodeB happened with pubsub:
     AggregateError: 
    Error: HOP request failed with code 260
        at hop (file:///libp2p/src/circuit/circuit/hop.js:147:17)
        at Circuit.dial (file:///libp2p/src/circuit/transport.js:150:33)
        at TransportManager.dial (file:///libp2p/src/transport-manager.js:[11](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/5193970522?check_suite_focus=true#step:6:11)1:[14](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/5193970522?check_suite_focus=true#step:6:14))
        at file:///libp2p/src/dialer/dial-request.js:81:[18](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/5193970522?check_suite_focus=true#step:6:18)
        at file:///p-some/index.js:53:[19](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/5193970522?check_suite_focus=true#step:6:19)
      at maybeSettle (file:///p-some/index.js:31:11)
      at file:///p-some/index.js:69:[23](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/5193970522?check_suite_focus=true#step:6:23)
```

it does not happen with libp2p 0.36.1. @wemeetagain any ideas?

_Originally posted by @tuyennhv in https://github.com/ChainSafe/js-libp2p-gossipsub/issues/186#issuecomment-1039816435_

**Comment by dapplion** [comment]
Tests have been re-worked
