### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#282]
CI is broken with this error

```
Test Browser
- Setting up chromium
Playwright build of chromium v978106 downloaded to /home/runner/.cache/ms-playwright/chromium-978106
Playwright build of ffmpeg v1007 downloaded to /home/runner/.cache/ms-playwright/ffmpeg-1007
✔ chromium set up
Error: R] Could not resolve "mocha/mocha-es2018.js"
    node_modules/playwright-test/src/setup-mocha.js:6:18:
      6 │ import mocha from 'mocha/mocha-es2018.js'
        ╵                   ~~~~~~~~~~~~~~~~~~~~~~~
  You can mark the path "mocha/mocha-es2018.js" as external to exclude it from the bundle, which will remove this error.
✖ Running tests failed.
Error: Build failed with 1 error:
node_modules/playwright-test/src/setup-mocha.js:6:18: ERROR: Could not resolve "mocha/mocha-es2018.js"
    at failureErrorWithLog (/home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:1599:15)
    at /home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:1[24](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/6895375292?check_suite_focus=true#step:5:25)5:28
    at runOnEndCallbacks (/home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:1030:63)
    at buildResponseToResult (/home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:1243:7)
    at /home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:1352:14
    at /home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:662:9
    at handleIncomingPacket (/home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:759:9)
    at Socket.readFromStdout (/home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/playwright-test/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:5[27](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/6895375292?check_suite_focus=true#step:5:28):[28](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/6895375292?check_suite_focus=true#step:5:29))
    at addChunk (node:internal/streams/readable:[31](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/6895375292?check_suite_focus=true#step:5:32)5:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "mocha/mocha-es2018.js"'
    }
  ],
  warnings: []
}
Command failed with exit code 1: pw-test ./dist/test/*.spec.js --mode main --config /home/runner/work/js-libp2p-gossipsub/js-libp2p-gossipsub/node_modules/aegir/src/config/pw-test.js --exit --timeout=60000 --bail
```

**Comment by tuyennhv** [comment]
I cannot reproduce in my local environment, I wonder it's due to some dependencies updated? @achingbrain @wemeetagain should we upgrade `aegir` to latest version?

**Comment by achingbrain** [comment]
It's expecting the `build` npm command to be `aegir build` which supports the `--no-bundle` flag (may be an overreach, we could not pass the flag in aegir).

I see there are two `tsconfig.json` files in this repo - if you just have one and use `aegir build` as your `build` script as per the convention it'll start to work.

The default `tsconfig.json` for a typescript project is [pretty simple](https://github.com/libp2p/js-libp2p-tcp/blob/master/tsconfig.json), any extra fields can be PR'd into [aegir/src/config/tsconfig.aegir.json](https://github.com/ipfs/aegir/blob/master/src/config/tsconfig.aegir.json) (we talked about turning on `noImplicitReturns`, for example).
